package de.hsmannheim.ss18.gae.imao.model;

public enum EGeraet {
 ULTRASCHALL_ALT, ULTRASCHALL_NEU, EINMALHANDSCHUE_NORMAL, EINMALHANDSCHUE_BESSER, DESINFEKTION, MIKROSKOP, SPRITZE_NORMAL, SPRITZE_BESSER, HAEMATOLOGIEGERAET  
}
