package de.hsmannheim.ss18.gae.imao.model;

public enum ESymptom {
	JUCKREITZ, FIEBER_NORMAL, FIEBER_LANG, FIEBER_HOCH_WECHSELHAFT, HARNWEGSBEFALL, EINSTICHSTELLE_KNOETCHENBILDUNG, EINSTICHSTELLE_BEULE, HUSTEN, SCHUPFEN, BINDEHAUTENTZUENDUNG, DURCHFALL, BRECHDURCHFALL, MUEDIGKEIT, ERBRECHEN_UEBELKEIT, ERBRECHEN_BLUT, VOELLEGEFUEHL, HAUT_GELB, AUGEN_GELBFAERBUNG, URIN_BRAUN, STUHL_HELL, MUSKELSCHMERZEN, KIEFERSPERRE, SCHLUCKSTOERUNG, ATEMSTOERUNG, GESICHTSMUSKELKRAEMPFE, BLUTUNG, SCHUETTELFROST, GELENKSCHMERZEN, PULS_NIEDRIG, NACHTSCHWEIS, LYMPHKNOTEN_GESCHWOLLEN, GEWICHTSVERLUST

}
